try {
    console.log(value)

} catch (err) {
    console.log(err)

} finally {
    console.log("Fim")
}